
name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main", "dev", "prod", "prod_support", "systest" ]

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        # Checks out the code from the repository

      - name: Set up JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Maven Package
        run: mvn -B clean package -DskipTests

      - name: Maven Verify
        run: mvn -B clean verify

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        # Checks out the code from the repository

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker image
        id: build-image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:latest
